# Generated by Django 5.2 on 2025-06-12 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=250)),
                ('especialidad', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=250)),
                ('horario_semana_inicio', models.TimeField()),
                ('horario_semana_fin', models.TimeField()),
                ('horario_sabado_inicio', models.TimeField()),
                ('horario_sabado_fin', models.TimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='nombre',
            new_name='tipo_consulta',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=250),
        ),
        migrations.AddField(
            model_name='turno',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_consulta', models.CharField(max_length=250)),
                ('notas', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
